# Generated by Django 5.0.6 on 2026-09-12 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('shooter', 'Shooter'), ('sports', 'Sports'), ('racing', 'Racing'), ('strategy', 'Strategy'), ('horror', 'Horror'), ('accessories', 'Accessories'), ('consoles', 'Consoles')], default='action', max_length=20)),
                ('brand', models.CharField(default='Generic', max_length=100)),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps5', 'PlayStation 5'), ('ps4', 'PlayStation 4'), ('xbox', 'Xbox Series X/S'), ('switch', 'Nintendo Switch'), ('multi', 'Multi-Platform')], default='pc', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
